/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ihusr.application;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import org.json.simple.parser.ParseException;
import org.json.simple.parser.ParseException;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import javax.swing.JFrame;
import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import java.io.FileReader;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.sql.*;
import java.util.Arrays;
import java.util.Map;
import java.util.Objects;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form HomeForm
     */
    
    int x,y;
    public HomeForm()
    {
        initComponents();
        
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
        
        home.setIcon(new ImageIcon("gui/homeS.png"));
        
        searchText.setVisible(false);
        searchGraphic.setVisible(false);

        username.setText(LoginForm.user.name);
        
        //Rec status 
        statusRecOpen1.setVisible(false);
        statusRecOpen2.setVisible(false);
        statusRecClose1.setVisible(false);
        statusRecClose2.setVisible(false);





    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleBarPanel = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        recommended = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        statusRecOpen1 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        searchText = new javax.swing.JTextField();
        searchGraphic = new javax.swing.JLabel();
        topLabel = new javax.swing.JLabel();
        categoriesLabel = new javax.swing.JLabel();
        notifications = new javax.swing.JButton();
        settings = new javax.swing.JButton();
        home = new javax.swing.JButton();
        user = new javax.swing.JButton();
        favourites1 = new javax.swing.JButton();
        welcomeText1 = new javax.swing.JLabel();
        foodCategory = new javax.swing.JLabel();
        coffeeGraphic = new javax.swing.JLabel();
        recName1 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        recName2 = new javax.swing.JLabel();
        recRating2 = new javax.swing.JLabel();
        recRating3 = new javax.swing.JLabel();
        statusRecClose1 = new javax.swing.JLabel();
        statusRecOpen2 = new javax.swing.JLabel();
        statusRecClose2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBarPanel.setBackground(new java.awt.Color(204, 204, 255));
        titleBarPanel.setForeground(new java.awt.Color(204, 204, 255));
        titleBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarPanelMouseDragged(evt);
            }
        });
        titleBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarPanelMousePressed(evt);
            }
        });
        titleBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon("gui/newCloseBlue.png")); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        titleBarPanel.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, -1, 30));

        minimize1.setIcon(new javax.swing.ImageIcon("gui/newMinimizeBlue.png")); // NOI18N
        minimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize1MouseClicked(evt);
            }
        });
        titleBarPanel.add(minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 20, 30));

        jPanel1.add(titleBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        jButton5.setForeground(new java.awt.Color(88, 101, 242));
        jButton5.setIcon(new javax.swing.ImageIcon("gui/userProfileOneS.png")); // NOI18N
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, 80));

        username.setBackground(new java.awt.Color(46, 46, 46));
        username.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(46, 46, 46));
        username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        username.setText(" User");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 220, 20));

        recommended.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        recommended.setForeground(new java.awt.Color(220, 220, 220));
        recommended.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recommended.setText("YOU CAN GO...");
        recommended.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        recommended.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recommendedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recommendedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recommendedMouseExited(evt);
            }
        });
        jPanel1.add(recommended, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, 40));

        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon("gui/logout.png")); // NOI18N
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 690, 60, 60));

        statusRecOpen1.setBackground(new java.awt.Color(46, 46, 46));
        statusRecOpen1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        statusRecOpen1.setForeground(new java.awt.Color(0, 153, 102));
        statusRecOpen1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusRecOpen1.setText("open");
        jPanel1.add(statusRecOpen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 660, 40, 20));

        search.setBackground(new java.awt.Color(255, 255, 255));
        search.setIcon(new javax.swing.ImageIcon("gui/search.png")); // NOI18N
        search.setBorder(null);
        search.setContentAreaFilled(false);
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 70, 40, 30));

        searchText.setBackground(new java.awt.Color(225, 225, 225));
        searchText.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        searchText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchText.setText("WHERE DO YOU WANT TO GO?");
        searchText.setBorder(null);
        searchText.addFocusListener(new java.awt.event.FocusAdapter(){
            public void focusGained(java.awt.event.FocusEvent evt){
                searchTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt){
                searchTextFocusLost(evt);
            }

        });
        searchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextActionPerformed(evt);
            }
        });
        jPanel1.add(searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 370, 30));

        searchGraphic.setIcon(new javax.swing.ImageIcon("gui/searchbar.png")); // NOI18N
        jPanel1.add(searchGraphic, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, -1, -1));

        topLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        topLabel.setForeground(new java.awt.Color(159, 159, 159));
        topLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topLabel.setText("APPLICATION'S USER");
        topLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        topLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                topLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                topLabelMouseExited(evt);
            }
        });
        jPanel1.add(topLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 150, 30));

        categoriesLabel.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        categoriesLabel.setForeground(new java.awt.Color(220, 220, 220));
        categoriesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categoriesLabel.setText("CHECK IT OUT...");
        categoriesLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        categoriesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categoriesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categoriesLabelMouseExited(evt);
            }
        });
        jPanel1.add(categoriesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 40));

        notifications.setBackground(new java.awt.Color(255, 255, 255));
        notifications.setIcon(new javax.swing.ImageIcon("gui/bell.png")); // NOI18N
        notifications.setBorder(null);
        notifications.setContentAreaFilled(false);
        notifications.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(notifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 60, -1, 50));

        settings.setBackground(new java.awt.Color(255, 255, 255));
        settings.setIcon(new javax.swing.ImageIcon("gui/settings.png")); // NOI18N
        settings.setBorder(null);
        settings.setContentAreaFilled(false);
        settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, -1, -1));

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.ImageIcon("gui/home.png")); // NOI18N
        home.setBorder(null);
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 50, 50));

        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setIcon(new javax.swing.ImageIcon("gui/user.png")); // NOI18N
        user.setBorder(null);
        user.setContentAreaFilled(false);
        user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 50, 50));

        favourites1.setBackground(new java.awt.Color(255, 255, 255));
        favourites1.setIcon(new javax.swing.ImageIcon("gui/love.png")); // NOI18N
        favourites1.setBorder(null);
        favourites1.setContentAreaFilled(false);
        favourites1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        favourites1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favourites1ActionPerformed(evt);
            }
        });
        jPanel1.add(favourites1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 50, 50));

        welcomeText1.setBackground(new java.awt.Color(46, 46, 46));
        welcomeText1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        welcomeText1.setForeground(new java.awt.Color(46, 46, 46));
        welcomeText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeText1.setText("Welcome");
        jPanel1.add(welcomeText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 100, -1));

        foodCategory.setIcon(new javax.swing.ImageIcon("gui/foodCategory.png")); // NOI18N
        foodCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        foodCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                foodCategoryMouseEntered(evt);
            }
        });
        jPanel1.add(foodCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        coffeeGraphic.setIcon(new javax.swing.ImageIcon("gui/coffeeCategory.png")); // NOI18N
        coffeeGraphic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(coffeeGraphic, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        recName1.setBackground(new java.awt.Color(42, 48, 116));
        recName1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        recName1.setForeground(new java.awt.Color(42, 48, 116));
        recName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        recName1.setText("name");
        jPanel1.add(recName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 160, 20));

        icon1.setIcon(new javax.swing.ImageIcon("gui/coffeeIslandIcon.png")); // NOI18N
        jPanel1.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 270, 130));

        icon2.setIcon(new javax.swing.ImageIcon("gui/todayIcon.png")); // NOI18N
        jPanel1.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 210, 150));

        recName2.setBackground(new java.awt.Color(42, 48, 116));
        recName2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        recName2.setForeground(new java.awt.Color(42, 48, 116));
        recName2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        recName2.setText("name");
        jPanel1.add(recName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 230, 20));

        recRating2.setBackground(new java.awt.Color(46, 46, 46));
        recRating2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        recRating2.setForeground(new java.awt.Color(224, 174, 29));
        recRating2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        recRating2.setText("rating");
        jPanel1.add(recRating2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 645, 150, 20));

        recRating3.setBackground(new java.awt.Color(46, 46, 46));
        recRating3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        recRating3.setForeground(new java.awt.Color(224, 174, 29));
        recRating3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        recRating3.setText("rating");
        jPanel1.add(recRating3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 645, 150, 20));

        statusRecClose1.setBackground(new java.awt.Color(46, 46, 46));
        statusRecClose1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        statusRecClose1.setForeground(new java.awt.Color(255, 102, 102));
        statusRecClose1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusRecClose1.setText("close");
        jPanel1.add(statusRecClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, 40, 20));

        statusRecOpen2.setBackground(new java.awt.Color(46, 46, 46));
        statusRecOpen2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        statusRecOpen2.setForeground(new java.awt.Color(0, 153, 102));
        statusRecOpen2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusRecOpen2.setText("open");
        jPanel1.add(statusRecOpen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 660, 40, 20));

        statusRecClose2.setBackground(new java.awt.Color(46, 46, 46));
        statusRecClose2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        statusRecClose2.setForeground(new java.awt.Color(255, 102, 102));
        statusRecClose2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusRecClose2.setText("close");
        jPanel1.add(statusRecClose2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 660, 40, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void recommendedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recommendedMouseClicked
        // TODO add your handling code here:  
    }//GEN-LAST:event_recommendedMouseClicked

    private void titleBarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarPanelMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_titleBarPanelMousePressed

    private void titleBarPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarPanelMouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_titleBarPanelMouseDragged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton5MouseEntered

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm();
        loginForm.show();
        dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_logoutMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(HomeForm.ICONIFIED);
    }//GEN-LAST:event_minimize1MouseClicked

    private void recommendedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recommendedMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_recommendedMouseEntered

    private void recommendedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recommendedMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_recommendedMouseExited

    private void topLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_topLabelMouseClicked

    private void topLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_topLabelMouseEntered

    private void topLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_topLabelMouseExited

    private void categoriesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriesLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriesLabelMouseClicked

    private void categoriesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriesLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriesLabelMouseEntered

    private void categoriesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriesLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriesLabelMouseExited

    private void searchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        home.setIcon(new ImageIcon("gui/homeS.png"));
        //home.setBounds(25, 285, 50, 50);
        user.setIcon(new ImageIcon("gui/user.png"));
        favourites1.setIcon(new ImageIcon("gui/love.png"));


        searchText.setVisible(false);
        searchGraphic.setVisible(false);
        
    }//GEN-LAST:event_homeActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        //User Button

        user.setIcon(new javax.swing.ImageIcon("gui/userS.png"));
        //user.setBounds(25, 335, 50, 50);

        home.setIcon(new javax.swing.ImageIcon("gui/home.png"));
        favourites1.setIcon(new javax.swing.ImageIcon("gui/love.png"));

        searchText.setVisible(false);
        searchGraphic.setVisible(false);


    }//GEN-LAST:event_userActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        //Search Button

        search.setLocation(725, 70);
        searchText.setVisible(true);
        searchGraphic.setVisible(true);
        searchText.setText("WHERE DO YOU WANT TO GO?");


    }//GEN-LAST:event_searchActionPerformed

    private void favourites1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favourites1ActionPerformed
        // TODO add your handling code here:
        //Favourites Button

        favourites1.setIcon(new javax.swing.ImageIcon("gui/heartS.png"));
        

        home.setIcon(new javax.swing.ImageIcon("gui/home.png"));
        user.setIcon(new javax.swing.ImageIcon("gui/user.png"));

        searchText.setVisible(false);
        searchGraphic.setVisible(false);

    }//GEN-LAST:event_favourites1ActionPerformed

    private void searchTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusGained
        // TODO add your handling code here:

        if(searchText.getText().equals("WHERE DO YOU WANT TO GO?")) {
            searchText.setText(null);
            searchText.requestFocus();
            searchText.setVisible(true);
        }

        searchText.setForeground(Color.BLACK);


    }//GEN-LAST:event_searchTextFocusGained

    private void searchTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFocusLost
        // TODO add your handling code here:

        if(searchText.getText().length() == 0) {
            searchText.setVisible(false);
            searchText.setText("WHERE DO YOU WANT TO GO?");
        }

        searchText.setForeground(Color.GRAY);

    }//GEN-LAST:event_searchTextFocusLost

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_homeMouseClicked

    private void foodCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodCategoryMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_foodCategoryMouseEntered

    /**
     * @param args the command line arguments
     */



    public static void main(String args[]) throws IOException , ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        JSONParser jsonParser = new JSONParser();
        JSONObject jsonObject = (JSONObject) jsonParser.parse(new FileReader(".idea//httpRequests//cafe_serres.json"));
        JSONArray jsonArray = (JSONArray) jsonObject.get("results");


        String[] shopNames = new String[18];
        String[] shopOpening = new String[18];
        Double[] shopRate = new Double[18];
        int shopID = 0;
        
        for(int i=0;i<jsonArray.size();i++)
        {

            JSONObject jsonObject1 = (JSONObject) jsonArray.get(i);

            String name = (String) jsonObject1.get("name");
            System.out.println("Name: " + name);

            Map<Object, Object> opening_hours = (Map<Object, Object>) jsonObject1.get("opening_hours");
            opening_hours.forEach((key, value) -> System.out.println(key + ": " + value));

            String business_status = (String) jsonObject1.get("business_status");
            System.out.println("Buissness status:"+business_status);

            double rating = (double) jsonObject1.get("rating");
            System.out.println("Rating:"+rating);

            String vicinity= (String) jsonObject1.get("vicinity");
            System.out.println("Vicinity: " + vicinity);

            shopID++;
            System.out.println(shopID);

            shopNames[i] = name;
            shopRate[i] = rating;
            shopOpening[i] = opening_hours.toString();

            addShopToDatabase(shopID,name, opening_hours.toString(), business_status,rating,vicinity);

        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                //Api api = new Api();
                new HomeForm().setVisible(true);

                //<editor-fold defaultstate="collapsed" desc=" Coffee Island ">
                recName1.setText(shopNames[4]);
                recRating3.setText(shopRate[4].toString());

                if(shopOpening[4].equals("{\"open_now\":true}"))
                {
                    statusRecOpen1.setVisible(true);
                }
                else
                {
                    statusRecClose1.setVisible(true);
                    System.out.println("Hello");
                }
                //</editor-fold>

                //<editor-fold defaultstate="collapsed" desc="Today's ">
                recName2.setText(shopNames[13]);
                recRating2.setText(shopRate[13].toString());

                if(shopOpening[13].equals("{\"open_now\":true}"))
                {
                    statusRecOpen2.setVisible(true);
                }
                else
                {
                    statusRecClose2.setVisible(true);
                }
                //</editor-fold>

                System.out.println(Arrays.toString(shopOpening));
            }
        });


    }

    public static Shop addShopToDatabase(Integer shopID,String name, String open_now, String business_status, double rating, String vicinity)
    {

        Shop shop = null;
        final String DB_URL = "jdbc:mysql://localhost/testing?serverTimezone=UTC";
        final String USERNAME = "root";
        final String PASSWORD = "";

        try{
            Connection conn = DriverManager.getConnection(DB_URL, USERNAME, PASSWORD);

            Statement stmt = conn.createStatement();
            String sql = "INSERT INTO shops (ID,name, open_now, business_status, rating, vicinity) " +
                    "VALUES (?,?, ?, ?, ?, ?)";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setInt(1,shopID);
            preparedStatement.setString(2, name);
            preparedStatement.setString(3, open_now);
            preparedStatement.setString(4, business_status);
            preparedStatement.setDouble(5, rating);
            preparedStatement.setString(6, vicinity);

            //Inserting rows into the table
            int addedRows = preparedStatement.executeUpdate();
            if (addedRows > 0){
                shop = new Shop();
                shop.ID = shopID;
                shop.name = name;
                shop.open_now = open_now;
                shop.business_status = business_status;
                shop.rating = (float) rating;
                shop.vicinity = vicinity;
            }
            stmt.close();
            conn.close();
        }catch(Exception e){
            e.printStackTrace();
        }
        return shop;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoriesLabel;
    private javax.swing.JLabel close;
    private javax.swing.JLabel coffeeGraphic;
    private javax.swing.JButton favourites1;
    private javax.swing.JLabel foodCategory;
    private javax.swing.JButton home;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel minimize1;
    private javax.swing.JButton notifications;
    private static javax.swing.JLabel recName1;
    private static javax.swing.JLabel recName2;
    private static javax.swing.JLabel recRating2;
    private static javax.swing.JLabel recRating3;
    private javax.swing.JLabel recommended;
    private javax.swing.JButton search;
    private javax.swing.JLabel searchGraphic;
    private javax.swing.JTextField searchText;
    private javax.swing.JButton settings;
    private static javax.swing.JLabel statusRecClose1;
    private static javax.swing.JLabel statusRecClose2;
    private static javax.swing.JLabel statusRecOpen1;
    private static javax.swing.JLabel statusRecOpen2;
    private javax.swing.JPanel titleBarPanel;
    private javax.swing.JLabel topLabel;
    private javax.swing.JButton user;
    private javax.swing.JLabel username;
    private javax.swing.JLabel welcomeText1;
    // End of variables declaration//GEN-END:variables
}
