/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ihusr.application;

/**
 *
 * @author savvi
 */
public class PreferForm extends javax.swing.JFrame {

    /**
     * Creates new form PreferForm
     */
    public PreferForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Skip_Button = new javax.swing.JButton();
        Apply_Button = new javax.swing.JButton();
        Image3_Label = new javax.swing.JLabel();
        Image4_Label = new javax.swing.JLabel();
        Image2_Label = new javax.swing.JLabel();
        Image1_Label = new javax.swing.JLabel();
        Image6_Label = new javax.swing.JLabel();
        Image5_Label = new javax.swing.JLabel();
        Category1_Label = new javax.swing.JLabel();
        Text_Label = new javax.swing.JLabel();
        Image_Label = new javax.swing.JLabel();
        Category2_Label = new javax.swing.JLabel();
        Category3_Label = new javax.swing.JLabel();
        Category4_Label = new javax.swing.JLabel();
        Category5_Label = new javax.swing.JLabel();
        Category6_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(683, 384));

        Skip_Button.setBackground(new java.awt.Color(88, 101, 242));
        Skip_Button.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Skip_Button.setForeground(new java.awt.Color(255, 255, 255));
        Skip_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Skip_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Skip_Button.setLabel("Skip");
        Skip_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Skip_ButtonActionPerformed(evt);
            }
        });

        Apply_Button.setBackground(new java.awt.Color(55, 71, 243));
        Apply_Button.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Apply_Button.setForeground(new java.awt.Color(255, 255, 255));
        Apply_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Apply_Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Apply_Button.setLabel("Apply");
        Apply_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Apply_ButtonActionPerformed(evt);
            }
        });

        Image3_Label.setBackground(new java.awt.Color(255, 255, 255));
        Image3_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image3_Label.setText("ΕΙΚΟΝΑ #3");
        Image3_Label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Image3_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Image4_Label.setBackground(new java.awt.Color(255, 255, 255));
        Image4_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image4_Label.setText("ΕΙΚΟΝΑ #4");
        Image4_Label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Image4_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Image2_Label.setBackground(new java.awt.Color(255, 255, 255));
        Image2_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image2_Label.setText("ΕΙΚΟΝΑ #2");
        Image2_Label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Image2_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Image1_Label.setBackground(new java.awt.Color(255, 255, 255));
        Image1_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image1_Label.setText("ΕΙΚΟΝΑ #1");
        Image1_Label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Image1_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Image6_Label.setBackground(new java.awt.Color(255, 255, 255));
        Image6_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image6_Label.setText("ΕΙΚΟΝΑ #6");
        Image6_Label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Image6_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Image5_Label.setBackground(new java.awt.Color(255, 255, 255));
        Image5_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image5_Label.setText("ΕΙΚΟΝΑ #5");
        Image5_Label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Image5_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Category1_Label.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Category1_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Category1_Label.setText("ΚΑΤΗΓΟΡΙΑ #1");

        Text_Label.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Text_Label.setForeground(new java.awt.Color(159, 159, 159));
        Text_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text_Label.setText("Choose your Preferences\nby pressing the Categories\nyou Like , then we will\nsuggest the best choice\nfor you!"); // NOI18N
        Text_Label.setToolTipText("");
        Text_Label.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Image_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Image_Label.setText("ΕΔΩ ΙΣΩΣ ΘΑ ΜΠΕΙ ΕΙΚΟΝΑ");

        Category2_Label.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Category2_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Category2_Label.setText("ΚΑΤΗΓΟΡΙΑ #2");

        Category3_Label.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Category3_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Category3_Label.setText("ΚΑΤΗΓΟΡΙΑ #3");

        Category4_Label.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Category4_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Category4_Label.setText("ΚΑΤΗΓΟΡΙΑ #4");

        Category5_Label.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Category5_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Category5_Label.setText("ΚΑΤΗΓΟΡΙΑ #5");

        Category6_Label.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Category6_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Category6_Label.setText("ΚΑΤΗΓΟΡΙΑ #6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Category4_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Category5_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Image4_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Image5_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Image6_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Category6_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Image1_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Image2_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Category1_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Category2_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Category3_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Image3_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Image_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Text_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Skip_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apply_Button)))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Image3_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(Image2_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Image1_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Category3_Label)
                            .addComponent(Category2_Label)
                            .addComponent(Category1_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Image4_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(Image5_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Image6_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Category4_Label)
                            .addComponent(Category5_Label)
                            .addComponent(Category6_Label))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Text_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Image_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Apply_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Skip_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Skip_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Skip_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Skip_ButtonActionPerformed

    private void Apply_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Apply_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Apply_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreferForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apply_Button;
    private javax.swing.JLabel Category1_Label;
    private javax.swing.JLabel Category2_Label;
    private javax.swing.JLabel Category3_Label;
    private javax.swing.JLabel Category4_Label;
    private javax.swing.JLabel Category5_Label;
    private javax.swing.JLabel Category6_Label;
    private javax.swing.JLabel Image1_Label;
    private javax.swing.JLabel Image2_Label;
    private javax.swing.JLabel Image3_Label;
    private javax.swing.JLabel Image4_Label;
    private javax.swing.JLabel Image5_Label;
    private javax.swing.JLabel Image6_Label;
    private javax.swing.JLabel Image_Label;
    private javax.swing.JButton Skip_Button;
    private javax.swing.JLabel Text_Label;
    // End of variables declaration//GEN-END:variables
}
